### ISSUE TITLE
Titel "Abbildungsverzeichnis" und "Tabellenverzeichnis" auch im Englischen

### ISSUE THREAD

**Issue by bumpy-b** [dhbw-horb/latexVorlage#26]
Wenn ich in den Einstellungen (einstellungen.tex) die Dokumentensprache auf "en" setze, werden in der kompilierten PDF die Titel "Abbildungsverzeichnis" und "Tabellenverzeichnis" dennoch in deutsch aufgeführt. Hierzu konnte ich jedoch keine Anpassungsmöglichkeit in den Tex-Dateien finden...

Ist das ein Bug / bei anderen reproduzierbar oder muss ich bei mir im System irgendetwas ändern, das ich bisher übersehen habe?

**Comment by dolonnen** [comment]
Hallo bumby

Das Problem ist bekannt. Es ist auch beim Inhaltsverzeichnis so. Wenn ich jetzt wieder mehr Zeit habe, suche ich nach den Grund für das Problem. Hilfe und Hinweise sind natürlich jederzeit Willkommen.

Danke fürs melden

**Comment by bumpy-b** [comment]
Mir ist mittlerweile aufgefallen, dass bis auf Listings alle Verzeichnisse betroffen sind, also auch das Literaturverzeichnis. Vielleicht liegt es daran, dass die Listings-Überschrift ja manuell ganz unten in header.tex umbenannt wird:
`\renewcommand\lstlistlistingname{\langlistlistingname}`

Ich habe nun die [alte englische Vorlage](https://github.com/dhbw-horb/latexVorlageEnglisch) mit den meisten der seither dazugekommenen Funktionalitäten (bis auf die Sprachumstellung) erweitert und hier tritt das Problem nicht auf...

**Comment by dolonnen** [comment]
Danke. Der Unterschied lieg bei den Zeilen im header:
_\usepackage[english, ngerman]{babel}_
_\iflang{de}{\selectlanguage{ngerman}} % Paket babel benutzt neue deutsche Rechtschreibung_
_\iflang{en}{\selectlanguage{english}} % Paket babel benutzt Englisch_

Ich habe einen [neuen Branch] (https://github.com/dhbw-horb/latexVorlage/tree/englischeVerzeichnisse) angelegt in der ich das Problem gefixt habe. Es scheint zu funktionieren. Ich möchte das aber noch etwas testen, denn das Ändern bei den Spracheinstellungen rund um das Babel-Paket hat in der letzten Zeit für viel Ärger gesorgt. Wenn du willst, kannst du das auch noch mal auf Seiteneffekte etc. testen.

Gruß

**Comment by bumpy-b** [comment]
Ach, hätte ich mal vor ein paar Stunden hier reingeschaut...bin zwischenzeitlich zu der gleichen Erkenntnis gekommen, nur dass ich entweder `ngerman` oder `english` wähle, nicht deren Reihenfolge, womit ich anfangs kein Glück hatte:
```
\iflang{de}{\usepackage[ngerman]{babel}}
\iflang{en}{\usepackage[english]{babel}}
```
Diese Variante habe ich mit `en` und `de` getestet und sie funktioniert auch. Seiteneffekte habe ich keine festgestellt - nur muss man nach der Umstellung jeweils die temporären Dateien löschen, sonst gibt es Fehlermeldungen, weil er noch das jeweils andere Sprachpacket erwartet.

Diese und einige andere Änderungen sind in [meinem Fork](https://github.com/bumpy-b/latexVorlage) zu finden. Ich kann ja wieder einen Pull Request schicken.
