### ISSUE TITLE
1. Verwendung einer Abkürzung im Text - sollte inline ausgeschrieben werden statt in Fußnote

### ISSUE THREAD

**Issue by bumpy-b** [dhbw-horb/latexVorlage#27]
Bei der ersten Verwendung einer Abkürzung im Text sollte laut den Empfehlungen der DHBW die ausgeschriebene Version mit der Abkürzung in Klammern stehen, bei der Latex-Vorlage wird – zumindest bei mir – die ausgeschriebene Version nicht inline im Text, sondern in einer Fußnote dargestellt.
Ist dies gewollt und lässt sich das ändern?

**Comment by dolonnen** [comment]
Hallo bumpy

In der header.tex wird das dafür zuständige Paket mit der Option footnote eingebunden
*\usepackage[printonlyused,footnote]{acronym}*

Es wird also statt einer ausgeschriebenen Erklärung eine Fussnote erstellt. Wenn man diese Option rausnimmt, hat man das Verhalten, das du haben möchtest. 

Ich bin mir da etwas unschlüssig. Mir gefallen beide Varianten. Kommt dann auch immer auf die ausgeschriebene Version an. Kannst du mal bitte die Empfehlung der DHBW hier verlinken und reinkopieren?

Gruß

**Comment by bumpy-b** [comment]
Danke für den Tip! Habe die Option "footnote" aus der usepackage-Direktive herausgenommen und nun wird es wie gewünscht dargestellt.

In DHBWMOS_Text_Formalitäten_Aufbau_Technik_final_Version_4.0.pdf  ( [4-2013: Download Lerneinheit WissBASE IIc - Aufbau einer wissenschaftlichen Arbeit](https://openmoodle.dhbw-mosbach.de/mod/resource/view.php?id=276) ) des [Open-Moodle Kurses der DHBW Mosbach] (https://openmoodle.dhbw-mosbach.de/course/view.php?id=14) steht auf S. 8 (bzw. 11 im pdf):
"Bei der ersten Nennung wird der Begriff ausgeschrieben und die Abkürzung in Klammern dahinter gesetzt. Bei jeder weiteren Verwendung kann die Abkürzung dann verwerndet werden."
Es stehen auch zwei einschlägige Beispiele dabei.

Danke auch für den Link. Zur Verwendung hatte ich bereits etwas gefunden. Als Hilfestellung erscheint mir jedoch auch folgender Kommentar in "acronyms.tex" sinnvoll:
 ```latex
%nur verwendete Akronyme werden letztlich im Abkürzungsverzeichnis des Dokuments angezeigt
%Verwendung: \ac{'Kürzel'} (nur das erste mal wird es automatisch ausgeschrieben)
%			\acp{'Kürzel'} gibt Plural aus (angefügtes 's')
%			siehe auch: http://golatex.de/wiki/%5Cacronym
```
