### ISSUE TITLE
automatisches Einbinden der Kapitel tex-Dateinen funktioniert nicht richtig

### ISSUE THREAD

**Issue by bumpy-b** [dhbw-horb/latexVorlage#30]
scheinbar kann pgffor die Indizierung `01,...,99` nicht automatisch auffüllen, da auf diese Art nur kapitel 1 und (falls vorhanden) 99 eingebunden wird. 
Zurzeit muss man also manuell jede Kapitelnummer in den Index einfügen: `\foreach \i in {01,02,03,04,05,06,...,99} `, dass ist ja bestimmt nicht so gedacht?!

Als schnelle Lösung fällt mir gerade folgende Variante ein, die jedoch maximal 9 Kapiteldateien zulässt.
```
	\foreach \i in {1,...,9} {%
		\edef\FileName{content/0\i kapitel}%
			\IfFileExists{\FileName}{%
				\input{\FileName}
			}
			{%
				%file does not exist
			}
	}
```
Alternative kann man natürlich auch die Dateinamen auf 1kapitel.tex, 2kapitel.tex, ... umbenennen und den Code dann wie folgt anpassen:
```
	\foreach \i in {1,...,99} {%
		\edef\FileName{content/\i kapitel}%
			\IfFileExists{\FileName}{%
				\input{\FileName}
			}
			{%
				%file does not exist
			}
	}
```

**Comment by Chaosprogrammierer** [comment]
du musst nur 01-09 schreiben, da pgffor nur integer zu kennen scheint und demzufolge eine 9 oder 8 sucht, anstatt 08,09.Das heißt, dies funktioniert so:

\foreach \i in {01,02,03,04,05,06,07,08,09,...,99} {%
        \edef\FileName{content/0\i kapitel}%
            \IfFileExists{\FileName}{%
                \input{\FileName}
            }
            {%
                %file does not exist
            }
    }

bei der vorherigen Version hatte es demzufolge 01,02,03,4,5,...99 erkannt und nun korrekt 01,02,03,04,05,...,99
Dies war mir in der letzten Praxisphase schon aufgefallen, hatte bloß nie Zeit das zu ändern .

**Comment by dolonnen** [comment]
Super, das klappt. Ich hab das sowohl im Master als im Branch pr-bumpy-b, der gerade getestet wird, geändert.

Danke
