### ISSUE TITLE
Verbesserungsvorschlag TOC

### ISSUE THREAD

**Issue by Slavic** [dhbw-horb/latexVorlage#33]
Hallo,

ich hatte bei mir das "Problem" das ich gerne ein TOC ohne Seitenzahlen wollte weil es für mich keine Sinn gemacht hat dort Seitenzahlen zu haben die ja nicht angezeigt werden. Ich musste lange probieren weil ich immer das Problem hatte dass, sobald das TOC über mehr als eine Seite lang war, nur die Letzte Seite keine Seitenzahl hatte. Nach einigem Suchen habe ich diese Lösung hier gefunden:
```
% Inhaltsverzeichnis
\begin{spacing}{1.1}
	\begingroup
		\renewcommand*{\chapterpagestyle}{empty}
		\pagestyle{empty}
		\setcounter{tocdepth}{2}
		\tableofcontents
		\clearpage
	\endgroup
\end{spacing}
```

vielleicht könntet ihr das Optional mit rein nehmen damit man sich im Fall das man es braucht nicht ewig zu Tode sucht wie ich ;) (Der Trick war wohl die Gruppe und der chapterpagestyle. pagestyle allein hat nie gereicht)

Grüße,

Holger

**Comment by dolonnen** [comment]
Hallo Holger,

Danke dafür. Es wurde eingebaut. Ein Kommentar im Quellcode weißt darauf hin, dass man wieder Seitenzahlen unter dem Inhaltsverzeichnis bekommen kann.

Gruß
Dolonnen

**Comment by Slavic** [comment]
Hi Dolonnen,

super das es mit drin is.

Grüße & Close
