### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by dupps** [dhbw-horb/latexVorlage#34]
Hallo,

beim Kompilieren kommt es immer (mehrfach) zu folgender Fehlermeldung:

```
Undefined control sequence.
l.43 	\RedeclareSectionCommand
                              [beforeskip=\kapitelabstand]{chapter} % stellt...
```

Wenn ich die betroffene Zeile auskommentiere, läuft er sauber durch. Ist dies ein bekanntes Problem?

Viele Grüße
Bastian

**Comment by dolonnen** [comment]
Hallo dupps,

Nein, davon ist nichts bekannt. Tausend Dank für das Melden.

Ich kann den Fehler leider nicht nachstellen. Offensichtlich findet Latex den Befehl _\RedeclareSectionCommand_ nicht. Diesen Befehl ist anscheinend Teil von KOMA-Script. Und zwar laut Release-Notes ab Version 3.15 vom Januar 2015.

Hast du vielleicht ein älteres KOMA-Script?

**Comment by dupps** [comment]
Hallo dolonnen,

ich nutze TeX Live und habe es wie folgt installiert:
```
apt-get install texlive-full texlive-bibtex-extra biber
```

Wie kann man denn die Version des KOMA-Scripts herausfinden, bzw es updaten?

**Comment by dupps** [comment]
Ich habe den TeX Live-Manager zurückgesetzt...
http://askubuntu.com/questions/485514/how-to-properly-install-and-use-texlive-with-package-manager-in-14-04
... und konnte anschließend KOMA nachinstallieren. Jetzt läuft es sauber durch.

**Comment by dolonnen** [comment]
Ah super. Ich war schon am Verzweifeln, weil alle Anleitungen das Programm tlmgr benötigten und da du Tex Live über deine Distribution installiert hast, war dir dieser Weg versperrt.

Freut mich, dass es geht. Ich kann das hier also schließen.
