### ISSUE TITLE
Problem mit xcolor usepackage command

### ISSUE THREAD

**Issue by Slavic** [dhbw-horb/latexVorlage#35]
Hallo,

ich hab mir heute die aktuelle Version hier raus kopiert da ich mit meiner BA anfange.
Da ich die Vorlage auch schon bei meiner Studienarbeit verwendet habe und ein paar
Modifikationen gemacht habe, wollte ich die erst mal kopieren. Dabei gab es folgendes
Problem:

In der Studienarbeit habe ich das Paket xcolor um Optionen erweitert:
```latex
\usepackage[usenames,dvipsnames,table,xcdraw]{xcolor} 	%xcolor für HTML-Notation
```
Bei der aktuellen Version bekomme ich jetzt aber diesen Fehler:
```
! LaTeX Error: Option clash for package xcolor.
The package xcolor has already been loaded with options:
  []
There has now been an attempt to load it with options
  [usenames,dvipsnames,table,xcdraw]
Adding the global options:
  ,usenames,dvipsnames,table,xcdraw
to your \documentclass declaration may fix this.
```

Nach etwas googeln hab ich dann rausgefunden, dass irgendwo wohl xcolor schon indirekt mit geladen wird. Ich hab dann mein modifiziertes usepackage hin und her kopiert und rausgefunden, dass der Fehler durch den Befehl `\usepackage{pdfpages}` in der letzten Zeile der Einstellungen verursacht wird. Wie es aussieht wird mit pdfpages indirekt xcolor mit geladen. Vielleicht lässt sich das irgendwie verschieben damit man die Modifikationen selbst einfügen kann. Wenn nicht weis über dieses Issue zumindest jeder woran der Fehler liegt :)

Ich hab für mich jetzt einfach mein xcolor Paket vor dem pdfpages command gesetzt und es funktioniert :)

Grüße,

Holger

**Comment by wOOx92** [comment]
Hallo @Slavic,

bei mir trat das gleiche Problem auf. Ich habe es gelöst, indem ich das Paket `xcolor` im `header.tex` gleich nach `\documentclass` gesetzt habe:


```
\documentclass[<ganz viele Optionen>]{scrreprt}	% Koma-Script report-Klasse, fuer laengere Bachelorarbeiten alternativ auch: scrbook
\usepackage[table]{xcolor} 	% für HTML-Notation
```
