### ISSUE TITLE
Literaturverzeichnis wird nicht erstellt

### ISSUE THREAD

**Issue by BennetBartmann** [dhbw-horb/latexVorlage#37]
Hallo,

bei mir (Linux Mint, Standard Latex Distribution, fullinstall) wird das Literaturverzeichnis nicht generiert.

Bereits versucht habe ich
Latex dokumentation.tex
Bibtex dokumentation
Latex dokumentation.tex
Latex dokumentation.tex

von Hand auszuführen jedoch führt auch dies nicht zu einem Literaturverzeichnis:(
(Versucht ohne Änderungen an der Standard vorlage als auch an meinem Dokument.)

Mit freundlichen Grüßen
Bennet Bartmann

Edit: Biber ist auch installiert.

**Comment by BennetBartmann** [comment]
Ohne COMA Script funktioniert es auch nicht. Irgendwo sollte ein Hinweis hin dass dieses installiert werden muss. 
Resolved.

**Comment by dolonnen** [comment]
Ich bin im Moment im Ausland und habe wenig Zeit mich darum zu kümmern.
Aber du hast recht, das readme kann einen Hinweis auf die Notwendigkeit von
Komascribt vertragen. Danke für den Hinweis.

Gruß

Bennet Bartmann <notifications@github.com> schrieb am Di., 11. Aug. 2015
15:41:
