### ISSUE TITLE
Seite X von Y einfügen

### ISSUE THREAD

**Issue by jollepe** [dhbw-horb/latexVorlage#38]
Hallo,

wie kann ich im Fließtext anstatt der zentrierten aktuellen Seitenzahl, stattdessen Seite X von Y eintragen?

**Comment by johannesbottcher** [comment]
Crosspost http://tex.stackexchange.com/questions/261200/page-x-of-y-where-to-add-into-config#

**Comment by dolonnen** [comment]
Hi, Sorry für die doch recht späte Antwort ;)

Falls es dich noch interessiert: Die Kopf- und Fusszeilen werden derzeit noch nach Standard generiert. Wenn gewünscht kann ich den Stil der Kopf- und Fusszeilen von headings in scrheadings umstellen und Einstellungen dazu anbieten.

**Comment by jollepe** [comment]
Hi,

danke für deine Rückmeldung.
Hatte damals es auf dem gleichen Weg gemacht ;-)

BTW: Es gibt eine neue Prüfungsordnung.
Die Ehrenwörtliche Erklärung wurde überarbeitet.
Als Anlage habe ich dir mal meine Version der erklaerung.tex
begefügt. Die entspricht der aktuellen Prüfungsordnung.

Viele Grüße
Julian

Am 20.05.2016 um 01:04 schrieb dolonnen:
> Hi, Sorry für die doch recht späte Antwort ;)
> 
> Falls es dich noch interessiert: Die Kopf- und Fusszeilen werden derzeit
> noch nach Standard generiert. Wenn gewünscht kann ich den Stil der Kopf-
> und Fusszeilen von headings in scrheadings umstellen und Einstellungen
> dazu anbieten.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/dhbw-horb/latexVorlage/issues/38#issuecomment-220471044>
> 

%!TEX root = ../dokumentation.tex

\thispagestyle{empty}

%\section*{\langerklaerung}
\vspace*{2em}
\begin{framed} 
\begin{center} 
\textit{Erklärung}\\
\end{center}
Ich versichere hiermit, dass ich meine Studienarbeit mit dem
Thema \textit{\titel} selbstständig verfasst und keine anderen als die angegebenen Quellen und Hilfsmittel
benutzt habe.\newline\newline
Ich versichere zudem, dass die eingereichte elektronische Fassung mit der gedruckten Fassung
übereinstimmt.*
\newline
\newline
\small{* falls beide Fassungen gefordert sind}

\vspace{1cm}

 
 \begin{tabular}{lp{2em}l} 
 \hspace{5cm}   && \hspace{5cm} \\\cline{1-1}\cline{3-3} 
 Ort, Datum     && Unterschrift 
\end{tabular} 
\end{framed}

**Comment by dolonnen** [comment]
sehr toll. Vielen Dank.

**Comment by Spenhouet** [comment]
[Ehrenwörtliche Erklärung - Portal](https://studium.hb.dhbw-stuttgart.de/fileadmin/Campus_Horb/mb/Dokumente/Ehrenw%C3%B6rtliche_Erkl%C3%A4rung.doc)
