### ISSUE TITLE
Kommentarumgebung funktioniert nicht

### ISSUE THREAD

**Issue by Spenhouet** [dhbw-horb/latexVorlage#39]
Verwende TeXstudio und TexLive.
Bei mir funktioniert die Kommentarumgebung garnicht:

_% eine Kommentarumgebung "k" (Handhabe mit \begin{k}<Kommentartext>\end{k},_
_% Kommentare werden rot gedruckt). Wird \% vor excludecomment{k} entfernt,_
_% werden keine Kommentare mehr gedruckt._
_\usepackage{comment}_
_\specialcomment{k}{\begingroup\color{red}}{\endgroup}_
_%\excludecomment{k}_

**Für die Kommentare wäre das folgende ein Ersatz:**
_% \newcommand{\comment}[1]{}  %Kommentar ausblenden_
_\newcommand{\comment}[1]{\par {\bfseries \color{blue} #1 \par}} %Kommentar anzeigen_

Benutzen mit:
_\comment{Kommentar}_

**Zusätzlich wäre die Todoumgebung sehr nützlich:**
_% \usepackage[disable]{todonotes} %Todos ausblenden_
_\usepackage[draft]{todonotes}   %Todos anzeigen_

Benutzen mit:
Hier gibt es die Möglichkeit Todos für eine Zeile zu machen (mit Notiz an der Seite)
_\todo{Zeilen TODO}_
Oder auch innerhalb einer Zeile anzuzeigen
_\todo[inline]{TODO in der Zeile}_

Aber das beste ist, dass man sich eine Todoliste anzeigen kann:
\listoftodos

![Kommentare](http://i.stack.imgur.com/7BLjT.png)

Quelle: http://tex.stackexchange.com/a/73418/95657

**Comment by dolonnen** [comment]
Die Notizumgebung habe ich letztens auch eingebaut aber noch nicht hier commited. 965724c58244bc63c6966f8e41b2b74e5a7b3a77
Die Kommentarumgebung hat zuerst zu Fehlern geführt. War wohl ein Typo drin. Geht jetzt aber auch 8bef5a2a5c3a1d96a29a6460a6778bc6473965e8

Vielen Dank für die Anregungen und Verbesserungsvorschläge

**Comment by Spenhouet** [comment]
Sehr gut! Vielen Dank fürs einbauen.
