### ISSUE TITLE
Log wird von TeXstudio nicht gefunden

### ISSUE THREAD

**Issue by Spenhouet** [dhbw-horb/latexVorlage#40]
Das Log wird von latexmk in den Unterordner [Output] gelegt. TeXstudio kann das Log so nicht finden und dem entsprechend nicht anzeigen.

Eine Lösung ist, in den Einstellungen von TeXstudio unter "Erzeugen" für den zusätzlichen Suchpfad für das Log "Output/" zu setzen.

Eine bessere Lösung fände ich, wenn der "latexmkrc" Datei eine Zeile hinzugefügt wird, die am Ende das Log von Output ins Hauptverzeichnis kopiert.
Ich weiß leider nicht wie das geht und das Anpassen des "makefile" hat leider nicht funktioniert (weil ich nicht weiß wie man "make all" ausführt.

**Comment by dolonnen** [comment]
Sorry @Spenhouet für die späte Antwort. Ich war im Prüfungs- und Studienarbeitsstress.

Ich kann verstehen, dass du gerne ohne weitere Einstellungen das Log in TeXstudio bringen willst. Aber der Outputordner ist gerade eben dazu da, die ganzen Output- und Log-Dateien (und die gibt es ja reichlich) aus dem Hauptverzeichnis rauszuhalten. Dann sind die an einem extra für sie gedachten Ort und fluten nicht das Hauptverzeichnis. Es ist wohl die logischste Lösung TeXstudio zu zeigen, wo die Logs sind.

**Comment by Spenhouet** [comment]
Danke für die Rückmeldung.
Das Problem hat sich für mich erledigt da ich die Vorlage auf LuaTex umgestellt habe (Umlaute in keys verwendbar).

**Comment by dolonnen** [comment]
ok. sorry, dass ich dir nicht weiterhelfen konnte.
