### ISSUE TITLE
Erklärung auf Deutsch ist Pflicht

### ISSUE THREAD

**Issue by hbrgnr** [dhbw-horb/latexVorlage#45]
An der DHBW Stuttgart, Fakultät Informatik, ist die "Erklärung" in jedem Fall auf Deutsch zu verfassen, unabhängig davon, ob die Arbeit auf Deutsch oder Englisch geschrieben ist. [Quelle](http://studium.dhbw-stuttgart.de/informatik/studienbetrieb/bachelorarbeiten/abgabe/) hierzu.

Die DHBW Horb (zumindest was ich hierzu gefunden habe) scheint es ähnlich zu handhaben: [Quelle](https://studium.hb.dhbw-stuttgart.de/maschinenbau/studienbetrieb/bachelorarbeit/t2-3300-bachelorarbeit/), deutsche Erklärung ist dort verlinkt.

Mit anderen DHBWs/Fakultäten kenne ich mich nicht aus. Ich bin jedoch der Meinung, dass eine deutsche Erklärung immer der sicherste Weg ist. Daher schlage ich vor, die englische Übersetzung zu entfernen.

**Comment by dolonnen** [comment]
In Karlsruhe (Informatik-Studiengänge) muss sie dagegen leider auf Deutsch und Englisch sein. (http://www.dhbw.de/fileadmin/user/public/Dokumente/Portal/Richtlinien_Praxismodule_Studien_und_Bachelorarbeiten_JG2011ff.pdf Seite 21)

Es ist wirklich ärgerlich, dass die Formalien nicht DHBW-weit einheitlich geregelt ist. Wir sollten das also jetzt mal so lassen. Sorry @hbrgnr
