### ISSUE TITLE
Geänderte Prüfungsordnung Sep.2017

### ISSUE THREAD

**Issue by maexbower** [dhbw-horb/latexVorlage#49]
Seit September 2017 gibt es eine geänderte Version der Prüfungsordnung der Fakultät Technik der DHBW Stuttgart. 

[PO 20/17](https://www.dhbw-stuttgart.de/fileadmin/dateien/Amtliche_Bekanntmachungen/20_2017_Bekanntmachung_StuPrO_DHBW_Technik.pdf)

Die Formulierungen für den Sperrvermerk und die Selbstständigkeitserklärung weichen auch in dieser von der in dieser Vorlage ab. 
Auch wenn die vorhandene Formulierung umfangreicher ist, lässt die PO nach meinem Verständniss wenig Spielraum für andere Formulierungen.
Sollte die Vorlage an die PO angepasst werden, oder ist die Formulierung aus der Vorlage so abgesegnet?

**Comment by dolonnen** [comment]
Vielen Dank für den Hinweis. Ja, die Formulierung für den Sperrvermerk in der Vorlage sollte angepasst werden. Die Erklärung ist aber schon die, die in der verlinkten Prüfungsordnung gefordert wird, oder hab ich da was übersehen?

Ich habe jetzt jedenfalls den Sperrvermerk aktualisiert. Falls noch was nicht stimmt, bitte jederzeit gerne melden.
